name: Create a new release on tag creation

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      id: checkout_code
      uses: actions/checkout@v2

    - name: Set up Go
      id: setup_go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.21'

    - name: Build Go app for darwin-arm64
      id: build-darwin-arm64
      run: |
        GOOS=darwin GOARCH=arm64 go build -o mark\
          && tar -cvf mark-${{ github.ref_name }}-darwin-arm64.tar ./mark\
          && gzip mark-${{ github.ref_name }}-darwin-arm64.tar

    - name: Build Go app for darwin-amd64
      id: build-darwin-amd64
      run: |
        GOOS=darwin GOARCH=amd64 go build -o mark\
          && tar -cvf mark-${{ github.ref_name }}-darwin-amd64.tar ./mark\
          && gzip mark-${{ github.ref_name }}-darwin-amd64.tar

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload binary for darwin-arm64
      id: upload_darwin_arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./mark-${{ github.ref_name }}-darwin-arm64.tar.gz
        asset_name: mark-${{ github.ref_name }}-darwin-arm64.tar.gz
        asset_content_type: application/gzip
        
    - name: Upload binary for darwin-amd64
      id: upload_darwin_amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./mark-${{ github.ref_name }}-darwin-amd64.tar.gz
        asset_name: mark-${{ github.ref_name }}-darwin-amd64.tar.gz
        asset_content_type: application/gzip
